# Generated by Django 4.2.2 on 2023-09-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weight_lifting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weightlifting",
            name="reps",
            field=models.IntegerField(default="0"),
        ),
        migrations.AlterField(
            model_name="weightlifting",
            name="weight",
            field=models.IntegerField(default="0"),
        ),
    ]
