# Generated by Django 4.2.2 on 2023-08-31 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "exercise_type",
                    models.IntegerField(
                        choices=[
                            (0, "Weight-Lifting"),
                            (1, "Running"),
                            (2, "Endurance"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_exercise",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
