# Generated by Django 4.2.2 on 2023-09-07 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workout", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Running",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.CharField(default="00:00:00:0")),
                ("distance", models.FloatField(default="0.0")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_running",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workout_exercise",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_exercise_running",
                        to="workout.workoutexercise",
                    ),
                ),
            ],
        ),
    ]
